name: "Deploy Network"

on:
  pull_request:
    branches:
      - main
      - dev

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  DeployNetworkingServices:
    name: Execute Terraform Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Configure Terraform Values
        run: |
          cd scripts
          pip install boto3
          python3 terraform_values.py

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Apply
        run: |
          cd iac
          terraform init
          terraform deploy -auto-approve
